apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - cluster-scoped
resources:
  - cache-deployer-role.yaml
  - cache-deployer-rolebinding.yaml
  - cache-deployer-deployment.yaml
commonLabels:
  app: cache-deployer
images:
  - name: registry.cn-beijing.aliyuncs.com/kubeflow1_4/ml-pipeline_cache-deployer
    newTag: 1.7.0
