apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: registry.cn-beijing.aliyuncs.com/kubeflow1_4/ml-pipeline_workflow-controller:v3.1.6-patch-license-compliance
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
