apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-writer-deployment.yaml
  - metadata-writer-role.yaml
  - metadata-writer-rolebinding.yaml
  - metadata-writer-sa.yaml
images:
  - name: registry.cn-beijing.aliyuncs.com/kubeflow1_4/ml-pipeline_metadata-writer
    newTag: 1.7.0
