apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-grpc-configmap.yaml
  - metadata-grpc-deployment.yaml
  - metadata-grpc-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
  - metadata-grpc-sa.yaml
images:
  - name: registry.cn-beijing.aliyuncs.com/kubeflow1_4/ml-pipeline_metadata-envoy
    newTag: 1.7.0
